### PR TITLE
0.14: rewrite for binary names

### PR DESCRIPTION
**Pull request by rurban**
This is still WIP. The new `t/names.t` is still failing.

### CODE REVIEW

**Comment by karenetheridge** [comment]
I've added ppport.h to the distribution and added an `#!include` to Name.xs -- please rebase this commit!

`perl ppport.h` also suggested adding `#define NEED_sv_2pv_flags_GLOBAL`, which I did not add, as I don't know what effect this may have.

**Comment by ribasushi** [comment]
> This is still WIP. The new t/names.t is still failing.

@rurban Are there any news on this?

**Comment by rurban** [comment]
Nope. There are 2 errors still, and I was busy with my complete family which decided to come over and held me back for a few days, and then bringing back the necessary backcompat macros to Devel::PPPort.

1. It crashes at global destruction - wrong refcount, 
2. possible wrong tests (encodings) in names.t. Maybe even a bug in my rewrite.

**Comment by rurban** [comment]
Actually you are right with your 435e8dd0d (shipped in 5.13.7) observation. Thanks, I didn't know that binary names were supported for that long already!

**Comment by rurban** [comment]
binary is now ready to be merged. all tests on all version do pass
I've renamed `t/exotic_names.t` to `t/names.t`

**Comment by wchristian** [comment]
This pull request requires further discussion in https://rt.cpan.org/Ticket/Display.html?id=113054 before any other steps can be taken.

**Comment by wchristian** [comment]
Discussion has taken place, and the shape of things to come is known. Now for the shape of things in here.

I see that the issue around ' is largely addressed and needs only a small adjustment, which i can handle if need be. (Which is to remove the deprecation in 25.)

However, there are other pressing issues.

@rurban:

In the comments above @Leont and @ilmari pointed out four places in the code that i understand to have been in need of changes. Do any of these four still require changing or have they been adressed by subsequent commits?

**Comment by rurban** [comment]
> On Mar 15, 2016, at 8:17 PM, Christian Walde (Mithaldu) <notifications@github.com> wrote:
> 
> Discussion has taken place, and the shape of things to come is known. Now for the shape of things in here.
> 
> I see that the issue around ' is largely addressed and needs only a small adjustment, which i can handle if need be. (Which is to remove the deprecation in 25.)
> 
> However, there are other pressing issues.
> 
> @rurban:
> 
> In the comments above @Leont and @ilmari pointed out four places in the code that i understand to have been in need of changes. Do any of these four still require changing or have they been adressed by subsequent commits?

Do the work by yourself or let me do it. Asking unneeded silly questions doesn’t help when talking to developers. 
Reading is a required skill, even if it’s too hard for the toolchain gang.
I refuse to do the kinder gardening here. I already told everybody what I think of this mess and maintainership here.

Accept the patch or reject it or rewrite it. But don’t bother us with this hot air for another year.

**Comment by wchristian** [comment]
@rurban: It can only be accepted if you clarify whether everything has been done that needed to be done, and as of this point you have not clearly confirmed or denied that the last for issues raised by leont and ilmari have been addressed.

Do any of these four still require changing or have they been adressed by subsequent commits?

**Comment by rurban** [comment]
> Do any of these four still require changing or have they been adressed by subsequent commits?

Are you able to read the commit messages? Try it, it might help wonders.

I know writing emails is easier, but sometimes a little reading helps also.

**Comment by wchristian** [comment]
Ok, thank you for confirming they have been adressed.

I will be preparing this branch on top of master as a tentative dev release candidate then.

**Comment by karenetheridge** [comment]
This was incorporated into #8 and released in 0.16-TRIAL. Thanks!

**Pull request closed without merging**
