### PR TITLE
Failing test with exotic naming

### PR DESCRIPTION
**Pull request by ap**
Refactoring of #4.

### CODE REVIEW

**Comment by ap** [comment]
I had misrefactored the tests WRT the `'` package separator. Now fixed, plus they’re simplified further.

**Comment by rurban** [comment]
@ap: Did you find out when exactly ' as package seperator was finally deprecated? I couldn't find it in the various deltas. I believe it was around 5.14 or so.

**Comment by ribasushi** [comment]
@rurban It has not been deprecated. At most discouraged. Case in point: 

https://metacpan.org/source/SHAY/perl-5.20.2/cpan/Test-Simple/lib/Test/More.pm#L385

**Comment by rurban** [comment]
@ribasushi: You mentioned the `sub isn't = \&isnt` in `Test::More`. This is still broken currently and doesn't prove your point. On the contrary it proves my point.

This sub `isn't` cannot be used currently as it uses the absolute name `main::isn::t` and not the relative name `isn't`. It's not documented with this quirks. Nobody should use it. The Exporter cannot import it. You cannot use it as lexical. The global name is misleading.

Only when the deprecation is finally being finished it can be used. But since this is a cpan module it cannot be used neither, as it needs to be backwards compatible. Hence it has no place to be there in the first place other than warning people not to use it. My guess is that people have no idea what they are doing.

**Comment by ap** [comment]
> This sub isn't cannot be used currently

Yes it can.

````
$ perl -MTest::More=tests,1 -e "isn't 1, 0"
1..1
ok 1
````

It’s awful, yes. But that doesn’t mean it doesn’t work, or that you can just break it because you don’t *like* that it works. It was a stupid joke. And now it has to be supported.

> it uses the absolute name `main::isn::t` and not the relative name `isn't`.

No, it uses the absolute name `isn::t` – function `t` in package `isn`.

Sure, in some sense it uses the absolute name `main::isn::t` – in the same sense it *also* uses the absolute name `main::main::isn::t`, `main::main::main::isn::t`, etc. And in the same sense that the module is really called `main::Test::More`, etc.

> Nobody should use it.

I agree, but people did, and now we have to live with that.

> The Exporter cannot import it. You cannot use it as lexical.

Yes, obviously – since it uses an explicit package name.

> Only when the deprecation is finally being finished it can be used.

Wrong. See above.

> But since this is a cpan module it cannot be used neither, as it needs to be backwards compatible.

Exactly.

> Hence it has no place to be there in the first place other than warning people not to use it.

… and to keep code working that already uses it.

> My guess is that people have no idea what they are doing.

That is usually a good guess.

**Comment by karenetheridge** [comment]
This was incorporated into #8 and released in 0.16-TRIAL. Thanks!

**Pull request closed without merging**
