### PR TITLE
Failing test for exotic names in %DB::sub

### PR DESCRIPTION
**Pull request by haarg**
This has a test to demonstrate that %DB::sub isn't being populated correctly for sub names with wide characters or nulls.  When using aliased stash entries and globs, the %DB::sub entries are populated correctly.

### CODE REVIEW

**Comment by haarg** [comment]
I'm not qualified to fix this unfortunately.  Maybe @leont could take a look.

**Comment by rurban** [comment]
I almost fixed it in my Scalar-List-Utils:
See https://github.com/perl11/cperl/blob/master/cpan/Scalar-List-Utils/ListUtil.xs#L1627
but there's still a leak.

**Comment by Leont** [comment]
> This has a test to demonstrate that %DB::sub isn't being populated correctly for sub names with wide characters or nulls. When using aliased stash entries and globs, the %DB::sub entries are populated correctly.

This sounds like a perlbug to me :-/

**Comment by Leont** [comment]
Pushed a fix to exotic-db-sub, though it doesn't fix 5.8.

**Comment by haarg** [comment]
I've pushed some fixes/improvements to the test, as well as @leont's fix.  The test is now passing everywhere except 5.14, where null characters fail.

**Comment by Leont** [comment]
> I've pushed some fixes/improvements to the test, as well as @leont's fix. The test is now passing everywhere except 5.14, where null characters fail.

That makes sense, given [f2462604](http://perl5.git.perl.org/perl.git/commit/f246260499cb1d0203cb449bbdf048074a0126a9?f=hv.h)

**Comment by karenetheridge** [comment]
[This commit](http://perl5.git.perl.org/perl.git/commitdiff/f246260499cb1d0203cb449bbdf048074a0126a9) looks possibly like something Devel::PPPort could cover?

**Comment by rurban** [comment]
ether: theoretically yes, but ppport.h is still lacking the most basic 5.16 API changes for binary names. this new change is just trivial.

**Comment by Leont** [comment]
> This commit looks possibly like something Devel::PPPort could cover?

With pretty much the same limitations as the [back-compat code](https://github.com/p5sagit/Sub-Name/pull/9/commits/0e6758b42e0385d79ef56bf6a518e72213845f4d#diff-023d688b09c7eada1b32a14485a8cb55R29) in my patch

**Comment by Leont** [comment]
> I've pushed some fixes/improvements to the test, as well as @leont's fix. The test is now passing everywhere except 5.14, where null characters fail.

This is fixed in the latest version of my patch

**Comment by haarg** [comment]
This currently breaks 5.6 compatibility, but I imagine that will be relatively easy to fix given that we don't really need Unicode to "work" in 5.6.

@rurban do you see anything problems here?

If this lands, I'll be pushing it on to Sub::Util.

**Comment by rurban** [comment]
There are 3 5.6.2 problems:

use Exporter 5.57: 

add `our @ISA    = qw{Exporter};`)

use Test::More version 0.88
done_testing, use the plan instead.

sv_catpvn_flags(): add 
```
#ifndef sv_catpvn_flags
#define sv_catpvn_flags(b,n,l,f) sv_catpvn(b,n,l)
#endif
```

See https://github.com/rurban/sub-name/tree/exotic-db-sub-5.6

**Comment by karenetheridge** [comment]
I'd be happy to put out a trial release, this evening or whenever you all feel it's ready.

**Comment by Leont** [comment]
> See https://github.com/rurban/sub-name/tree/exotic-db-sub-5.6

Looks reasonable to me

**Comment by haarg** [comment]
@karenetheridge I believe this is ready for merge & trial release.

**Comment by karenetheridge** [comment]
This is merged and released as 0.22-TRIAL. Thanks!

**Pull request closed without merging**
